### ISSUE TITLE
Prerender appears to fail for Google

### ISSUE THREAD

**Issue by iJungleboy** [oqtane/oqtane.framework#1712]
We created [Oqtane.me](https://oqtane.me/) for oqtane developers, so they can quickly use mysite.oqtane.me and other domains for testing purposes. 

We were really looking forward to prerendering so that the site could also be found in google, but it appears that the current pre-rendering doesn't suffice. When researching the issues  these are some of our current findings:

Google Page Speed Insights usually helps us see how google sees it - but that results in an error: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Foqtane.me%2F

![image](https://user-images.githubusercontent.com/5321186/136463496-382b0633-a5f0-4488-819f-23b4b9f231dd.png)

We also tried Search Console but that too errored.

If we see a quick result in F12 in the preview, this is what Chrome gives us:
![image](https://user-images.githubusercontent.com/5321186/136463639-ba0a0ef3-d690-4cb5-a559-02c57886f76a.png)

My guess is that even though pre-render includes the text somewhere, it's not really visible for certain reasons, and that's why we get the `NO_FCP` error. I believe google says that the [**First Contentful Paint**](https://web.dev/first-contentful-paint/#:~:text=Appears%20in%3A%20Performance%20audits,aspect%20of%20page%20load%20speed.) never happens.

I believe that to resolve this, the following is necessary

1. Header changes - especially CSS which should be added - should also be applied for pre-render
2. This I believe is especially important for Theme CSS and JS but also for Modules

In case this is correct, I believe that we need to rethink how header-changes are applied. ATM there is a very-weakly-typed interop mechanism to add these things, and I believe we should provide a strongly typed implementation, which internally works on both the server and the client. 

Your thoughts?

**Comment by iJungleboy** [comment]
I know of those challenges - and am also hoping for .net 6, though I'm pretty sure it's near RTM so probably whatever is in there now won't change much any more. 

As of now, is there a way to add headers server-side in blazor (not necessarily Oqtane), or is there no such functionality? Does it always need the interop?

**Comment by sbwalker** [comment]
I think #1840 will improve the pre-rendering limitations. Specifically it migrates some of the logic for setting head elements such as title, etc... to the server which will make them accessible to web crawlers. In addition it populates the initial CSS references based on the theme for the page. And lastly, the JavaScript interop calls in ThemeBuilder were implemented in OnParametersSet which is not recommended practice, and can cause errors - especially during pre-rendering, so they were moved to OnAfterRender.

**Comment by sbwalker** [comment]
I believe this is resolved in the latest version

**Comment by iJungleboy** [comment]
I just checked and it still doesn't work. 

Basically pre-render is useless as long as we have `display: none` because the content will not be indexed by any spider in this scenario. 

I'm aware of the unsexy-flash of content problem, but I believe if we ever want to use Oqtane for any website, we must find a way to solve this.  

I see three options - and would also volunteer to implement them, if you agree to include it once it works:

1. We add an option to Oqtane to change this behavior for people who are willing to accept the flash
2. OR we implement it in a way that users get the `display: none` whereas the spiders/crawlers don't - maybe also with a toggle to enable this
3. Change the `App.razor` to only be a container for the real `AppImplementation.razor` or something, which could then either be configured or somehow dependency injected - this would allow users to override functionality it as needed

My preference is to implement 1. and 2. both with options, but 3. is also viable IMHO. 

Your thoughts?

**Comment by sbwalker** [comment]
@iJungleboy I do not believe this issue has anything to do with the "display: none;" attribute, as if this were true then spiders would not be able to index any content on any web page which use menus, tabs, accordions, etc... - all of which use this attribute to hide/show content dynamically. Spiders simply ingest the page output and index the content - they do not analyze the use of dynamic attributes.

In researching this item further, I used the www.oqtane.net site as an example...

1. I ran the site through the W3C validator (https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.oqtane.net%2F) which is essentially a spider of sorts as it relies on pre-rendered content - and although the service reports some validation issues, it is clear that it is able to ingest all of the page content 
2. I ran the site through Google Search Console (https://search.google.com/search-console/) and it did not report any issues with indexing the page content 
![image](https://user-images.githubusercontent.com/4840590/151707505-c9eadfa4-bd66-4e90-b48e-569b2a986b14.png)
3. I used the advanced Google search to search for keywords on the home page of the site to determine if they were in Google's search index (https://www.google.com/search?q=site%3Awww.oqtane.net+2sxc) and I received results back indicating that the page had been successfully indexed 
4. I used Google PageSpeed Insights (https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.oqtane.net%2F) and it does not report any issues
5. I used WebPageTest (https://webpagetest.org/) and it does not report any issues 

So I would conclude that pre-rendering is working as expected and there is no issue with the "display: none;" attribute.

It is possible that earlier versions of Oqtane did have some issues in regards to pre-rendering - which is why I indicated above that I believed #1840 may have resolved the issue. Note that https://www.oqtane.net is running the latest version of Oqtane 3.0.2 - perhaps you need to upgrade your installation?

**Comment by iJungleboy** [comment]
I'll update all our system and investigate further. 

Thanks for all your work on this - it's really important to us. 

I'll close for now, and re-open if I need to.
